/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_qlis;

import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import javax.swing.*;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author rodsa
 */
public class AddTestForm extends javax.swing.JFrame {
  MainFrame mf = new  MainFrame();
    /**
     * Creates new form AddTestForm
     */
    public AddTestForm() {
        initComponents();
//        UtilDateModel model = new UtilDateModel();
//JDatePanelImpl datePanel = new JDatePanelImpl(model);
//JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
// 
//frame.add(datePicker);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldTestName = new javax.swing.JTextField();
        jTextFieldTestDate = new javax.swing.JTextField();
        jTextFieldidTest = new javax.swing.JTextField();
        jTextFieldTestDescription = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldInsurance_Number = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTestButtonCancel = new javax.swing.JButton();
        jTestButtonAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        xClose = new javax.swing.JLabel();
        Hide = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jTextFieldTestName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldTestName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldTestDate.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldTestDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldidTest.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldidTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldTestDescription.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldTestDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(236, 240, 241));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("TestDate:");
        jLabel12.setAutoscrolls(true);

        jLabel13.setBackground(new java.awt.Color(236, 240, 241));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("idTest:");
        jLabel13.setAutoscrolls(true);

        jLabel14.setBackground(new java.awt.Color(236, 240, 241));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("TestName:");
        jLabel14.setAutoscrolls(true);

        jLabel15.setBackground(new java.awt.Color(236, 240, 241));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("TestDescription:");
        jLabel15.setAutoscrolls(true);

        jTextFieldInsurance_Number.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldInsurance_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setBackground(new java.awt.Color(236, 240, 241));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Insurance_Number:");
        jLabel16.setAutoscrolls(true);

        jTestButtonCancel.setBackground(new java.awt.Color(102, 153, 255));
        jTestButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTestButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jTestButtonCancel.setText("Cancel");
        jTestButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTestButtonCancelMouseClicked(evt);
            }
        });

        jTestButtonAdd.setBackground(new java.awt.Color(102, 153, 255));
        jTestButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTestButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jTestButtonAdd.setText("Add");
        jTestButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTestButtonAddMouseClicked(evt);
            }
        });
        jTestButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTestButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTestButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldTestDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldInsurance_Number, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTestDescription, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldidTest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldidTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTestDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldTestDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsurance_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTestButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        xClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xClose.setForeground(new java.awt.Color(255, 255, 255));
        xClose.setText("X");
        xClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xCloseMouseClicked(evt);
            }
        });

        Hide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hide.setForeground(new java.awt.Color(255, 255, 255));
        Hide.setText("_");
        Hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add TEST");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(Hide, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Hide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(xClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCloseMouseClicked

//            mf.setVisible(true);
//            mf.pack();
//            mf.setLocationRelativeTo(null);
            //mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_xCloseMouseClicked

    private void HideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_HideMouseClicked

    private void jTestButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonAddActionPerformed
        
//      int idTest;
//      String lname;
//      String tDate;
//      String tName;
//      String tDescription;
//      String InNum;  
//       
//      idTest= parseInt(jTextFieldidTest.getText());
//      tDate=jTextFieldTestDate.getText();
//      tName=jTextFieldTestName.getText();
//      tDescription=jTextFieldTestDescription.getText();
//      InNum=jTextFieldInsurance_Number.getText();
    
    }//GEN-LAST:event_jTestButtonAddActionPerformed

    private void jTestButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestButtonCancelMouseClicked
       
          mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
            mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_jTestButtonCancelMouseClicked

    private void jTestButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestButtonAddMouseClicked
       
//       int idTest;
//       String lname;
//       String tDate;
//       String tName;
//       String tDescription;
//       String InNum;
//       String query = "";
//        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/mm/yyyy");
//    
//        if(jTextFieldidTest.getText().equals("")|| 
//               jTextFieldTestDate.getText().equals("")|| 
//               jTextFieldTestName.getText().equals("")||
//               jTextFieldTestDescription.getText().equals("")||
//               jTextFieldInsurance_Number.getText().equals(""))
//      
//        {
//           JOptionPane.showMessageDialog(null, "We did'nt add information","Fill out Information",JOptionPane.ERROR_MESSAGE);
//       
//        }
//       else
//       {
//            idTest= parseInt(jTextFieldidTest.getText());
//            tDate=jTextFieldTestDate.getText();
//            tName=jTextFieldTestName.getText();
//            tDescription=jTextFieldTestDescription.getText();
//            InNum=jTextFieldInsurance_Number.getText();
//        
//               
//            query = "Insert INTO LabTest ";
//            query = query + "(TestID, TestDate, TestName, TestDescription, Insurance_Number)";
//            query = query + "Values";
//
//            query = query + "("+ parseInt(jTextFieldidTest.getText())
//                    + ", to_DATE('"+jTextFieldTestDate.getText()+"'"
//                    + ",'dd/mm/yyyy'),'" +jTextFieldTestName.getText()+"'"
//                    + ", '" +jTextFieldTestDescription.getText()+"'"
//                    + ", '" + jTextFieldInsurance_Number.getText()+"')";
//           System.out.println(query);
//           
//             ConnectJavaOracle.rs = ConnectJavaOracle.processSearchQuery(query);     
//       }
//        
//        ConnectJavaOracle.closeOracleConnection();
    }//GEN-LAST:event_jTestButtonAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hide;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jTestButtonAdd;
    private javax.swing.JButton jTestButtonCancel;
    private javax.swing.JTextField jTextFieldInsurance_Number;
    private javax.swing.JTextField jTextFieldTestDate;
    private javax.swing.JTextField jTextFieldTestDescription;
    private javax.swing.JTextField jTextFieldTestName;
    private javax.swing.JTextField jTextFieldidTest;
    private javax.swing.JLabel xClose;
    // End of variables declaration//GEN-END:variables
}
