/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_qlis;

import static java.lang.Integer.parseInt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.*;
import java.awt.print.*;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.JTable;
import static javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS;
import static javax.swing.JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {
   AddTestForm addfm;
   Register lf = new Register();
   PATIENT patient = new PATIENT();
   
   /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xClose = new javax.swing.JLabel();
        Hide = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SearchB = new javax.swing.JButton();
        CANCEL_B = new javax.swing.JButton();
        InsuranceNumberL = new java.awt.Label();
        INSURANCE_NUMBER_TF = new javax.swing.JTextField();
        DR_L1 = new java.awt.Label();
        DR_L = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddTest = new javax.swing.JTable();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldsIN = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        InsertB = new javax.swing.JButton();
        UpdateB = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        DeleteRowB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDesctiption = new javax.swing.JTextArea();
        InsuranceNumberL1 = new java.awt.Label();
        InsuranceNumberL2 = new java.awt.Label();
        InsuranceNumberL3 = new java.awt.Label();
        InsuranceNumberL4 = new java.awt.Label();
        InsuranceNumberL5 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        DR_L2 = new java.awt.Label();
        DRL = new java.awt.Label();
        PatientLastNameL = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        xClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xClose.setForeground(new java.awt.Color(255, 255, 255));
        xClose.setText("X");
        xClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xCloseMouseClicked(evt);
            }
        });

        Hide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hide.setForeground(new java.awt.Color(255, 255, 255));
        Hide.setText("_");
        Hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medical Laboratories Information System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 838, Short.MAX_VALUE)
                .addComponent(Hide, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Hide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 60));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        SearchB.setBackground(new java.awt.Color(102, 153, 255));
        SearchB.setForeground(new java.awt.Color(255, 255, 255));
        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        CANCEL_B.setBackground(new java.awt.Color(102, 153, 255));
        CANCEL_B.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL_B.setText("EXIT");
        CANCEL_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCEL_BActionPerformed(evt);
            }
        });

        InsuranceNumberL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL.setText("ENTER INSURANCE NUMBER:");

        INSURANCE_NUMBER_TF.setBackground(new java.awt.Color(108, 122, 137));
        INSURANCE_NUMBER_TF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DR_L1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DR_L1.setForeground(new java.awt.Color(255, 255, 255));
        DR_L1.setText("PATIENT NAME:");

        DR_L.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DR_L.setForeground(new java.awt.Color(255, 255, 255));
        DR_L.setText("DR.");

        jTableAddTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TestID", "TestDate", "TestName", "TestDescription", "Insurance_Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAddTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableAddTestFocusGained(evt);
            }
        });
        jTableAddTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAddTestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAddTest);

        jTextFieldID.setBackground(new java.awt.Color(108, 122, 137));

        jTextFieldDate.setBackground(new java.awt.Color(108, 122, 137));

        jTextFieldsIN.setBackground(new java.awt.Color(108, 122, 137));

        jTextFieldName.setBackground(new java.awt.Color(108, 122, 137));

        InsertB.setText("Insert");
        InsertB.setMaximumSize(new java.awt.Dimension(67, 23));
        InsertB.setMinimumSize(new java.awt.Dimension(67, 23));
        InsertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBActionPerformed(evt);
            }
        });

        UpdateB.setText("Update");
        UpdateB.setActionCommand("Insert");
        UpdateB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBMouseClicked(evt);
            }
        });
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        jButtonPrint.setText("Print Test");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        DeleteRowB.setText("Delete");
        DeleteRowB.setActionCommand("Insert");
        DeleteRowB.setMaximumSize(new java.awt.Dimension(67, 23));
        DeleteRowB.setMinimumSize(new java.awt.Dimension(67, 23));
        DeleteRowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRowBActionPerformed(evt);
            }
        });

        jTextAreaDesctiption.setColumns(20);
        jTextAreaDesctiption.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaDesctiption.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDesctiption);

        InsuranceNumberL1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL1.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL1.setName("TEST NAME"); // NOI18N
        InsuranceNumberL1.setText("REPORT ");

        InsuranceNumberL2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL2.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL2.setText("TEST ID");

        InsuranceNumberL3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL3.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL3.setName("TEST NAME"); // NOI18N
        InsuranceNumberL3.setText("TEST DATE");

        InsuranceNumberL4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL4.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL4.setName("TEST NAME"); // NOI18N
        InsuranceNumberL4.setText("INSURANCE NUMBER");

        InsuranceNumberL5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InsuranceNumberL5.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceNumberL5.setText("TEST NAME");

        DR_L2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DR_L2.setForeground(new java.awt.Color(255, 255, 255));

        DRL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DRL.setForeground(new java.awt.Color(248, 148, 6));

        PatientLastNameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PatientLastNameL.setForeground(new java.awt.Color(248, 148, 6));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDate)
                            .addComponent(jTextFieldID)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldsIN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(InsertB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(DeleteRowB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1))
                            .addComponent(jScrollPane2)
                            .addComponent(jTextFieldName)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsuranceNumberL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsuranceNumberL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsuranceNumberL4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsuranceNumberL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsuranceNumberL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsuranceNumberL, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(INSURANCE_NUMBER_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(SearchB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(DR_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PatientLastNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DR_L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(DR_L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DRL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CANCEL_B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(DR_L2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SearchB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(INSURANCE_NUMBER_TF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InsuranceNumberL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(DR_L1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PatientLastNameL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DR_L, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(InsuranceNumberL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsuranceNumberL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsuranceNumberL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsuranceNumberL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsuranceNumberL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldsIN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteRowB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(CANCEL_B, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        DR_L1.getAccessibleContext().setAccessibleName("");
        InsuranceNumberL1.getAccessibleContext().setAccessibleName("TEST NAME");
        InsuranceNumberL2.getAccessibleContext().setAccessibleName("TEST DATE");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 1480, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCloseMouseClicked
        ConnectJavaOracle.closeOracleConnection();
        int confirm = JOptionPane.showOptionDialog(this,
                        "Are You Sure to Close this Application?",
                        "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
       
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(1);
                }
    }//GEN-LAST:event_xCloseMouseClicked

    private void HideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_HideMouseClicked

    private void CANCEL_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCEL_BActionPerformed
       int confirm = JOptionPane.showOptionDialog(this,
                        "Are You Sure to Close this Application?",
                        "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
       
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(1);
                }
    }//GEN-LAST:event_CANCEL_BActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
     // ConnectJavaOracle.openOracleConnection("scott", "tiger"); 
      
        ClearTable();
       
      
       
        String query1 = "Select TestID, to_char(TestDate,'dd/mm/yyyy')as TestDate, TestName, TestDescription, Insurance_Number from LabTest where Insurance_Number = '"+INSURANCE_NUMBER_TF.getText()+"'";
       
        System.out.println(query1);//print on console
        System.out.println("Connecting to a selected database...");
        
            List<LinkedHashMap<String, Object>> records = ConnectJavaOracle.RetrieveRecords(query1);
            ConnectJavaOracle.rs = ConnectJavaOracle.processSearchQuery(query1);
            System.out.println(query1);//print on console
                try{
                    //while (ConnectJavaOracle.rs.next()){
                    
                        //InsNum = ConnectJavaOracle.rs.getString("Insurance_Number");
                      
                        int wTestID;
                        String wTestName;
                        String wTestDate;
                        String wTestDescription;
                        String wInsNumber;

                        int row=0;
                        
                        
                        if(records.size() == 0)
                            {
    
                                JOptionPane.showMessageDialog(null, "Patient doesn't have result","Information about Test Report",JOptionPane.INFORMATION_MESSAGE);
                            }
                        Object value;
                        for(LinkedHashMap<String, Object> record : records)
                        {
                            for(String key : record.keySet())
                            {
                                value = record.get(key);
                                System.out.println("key: " + key + ", value: " + value + ", type: " + value.getClass());
                            }
                        }
                     
                        while (ConnectJavaOracle.rs.next())
                        {
                            
                                
                            wTestID = ConnectJavaOracle.rs.getInt("TestID");
                            wTestDate = ConnectJavaOracle.rs.getString("TestDate").substring(0,10);
                            wTestName = ConnectJavaOracle.rs.getString("TestName");
                            wTestDescription = ConnectJavaOracle.rs.getString("TestDescription");
                            wInsNumber = ConnectJavaOracle.rs.getString("Insurance_Number");

                            System.out.println("db_TestID: "+ wTestID + " db_TestName: "+wTestName);
                            
                            if(ConnectJavaOracle.rs.getFetchSize() == 0)
                            {
                                System.out.println(wTestID);
                                JOptionPane.showMessageDialog(null, "Patient doesn't have result","Information about Test Report",JOptionPane.INFORMATION_MESSAGE);
                            }
                            else{
                                jTableAddTest.setValueAt(wTestID, row, 0);
                                jTableAddTest.setValueAt(wTestDate, row, 1);
                                jTableAddTest.setValueAt(wTestName, row, 2);
                                jTableAddTest.setValueAt(wTestDescription, row, 3);
                                jTableAddTest.setValueAt(wInsNumber, row, 4);
                            }
                            row++;

                        }  
                    
                   // }

                  }
                 catch (Exception e) {
                    ConnectJavaOracle.ErrorSearchMessage(e);
                    }
    }//GEN-LAST:event_SearchBActionPerformed
private void ClearTable()
{
    for(int row = 0; row < jTableAddTest.getRowCount(); row++){
        for(int col=0;col<5;col++){
            jTableAddTest.setValueAt("", row, col);
        }
    
    }
}
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void jTableAddTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAddTestMouseClicked
      
       int i = jTableAddTest.getSelectedRow();
       jTableAddTest.setAutoResizeMode(AUTO_RESIZE_SUBSEQUENT_COLUMNS);
       jTableAddTest.setRowHeight(20);
       jTextFieldID.setText(jTableAddTest.getValueAt(i, 0).toString());
       jTextFieldDate.setText(jTableAddTest.getValueAt(i, 1).toString());
       jTextFieldName.setText(jTableAddTest.getValueAt(i, 2).toString());
       jTextAreaDesctiption.setText(jTableAddTest.getValueAt(i, 3).toString());
       jTextFieldsIN.setText(jTableAddTest.getValueAt(i, 4).toString());
      
       if(LoginForm.role.equals("Patient"))
       {
            
            DeleteRowB.setEnabled(false);
            InsertB.setEnabled(false);
            UpdateB.setEnabled(false);
       }
       else
       {
            DeleteRowB.setEnabled(true);
            InsertB.setEnabled(true);
            UpdateB.setEnabled(true);
        
       }
       
    }//GEN-LAST:event_jTableAddTestMouseClicked

    private void InsertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBActionPerformed

     // ConnectJavaOracle.openOracleConnection("scott", "tiger");   
           
            try{
                
                    if(jTextFieldID.getText().equals("")|| 
                        jTextFieldDate.getText().equals("")|| 
                        jTextFieldName.getText().equals("")||
                        jTextAreaDesctiption.getText().equals("")||
                        jTextFieldsIN.getText().equals(""))
                        {
                            JOptionPane.showMessageDialog(null, "We didn't add Information","Please fill out Information",JOptionPane.ERROR_MESSAGE);
                        }else
                        {
                            String query = "Insert INTO LabTest ";
                            query = query + "(TestID, TestDate, TestName, TestDescription, Insurance_Number)";
                            query = query + "Values";

                            query = query + "("+ parseInt(jTextFieldID.getText())
                                    + ", to_DATE('"+jTextFieldDate.getText()+"'"
                                    + ",'dd/mm/yyyy'),'" +jTextFieldName.getText()+"'"
                                    + ", '" +jTextAreaDesctiption.getText()+"'"
                                    + ", '" + jTextFieldsIN.getText()+"')";
                           System.out.println(query);
                           ConnectJavaOracle.rs = ConnectJavaOracle.processSearchQuery(query);  
                           JOptionPane.showMessageDialog(null, "We insert test successfully","Insert",JOptionPane.INFORMATION_MESSAGE);
                        }
                     
                }catch (Exception e) {
                    ConnectJavaOracle.ErrorSearchMessage(e);
                            if(ConnectJavaOracle.ErrorType == 1)
                            {
                                   JOptionPane.showMessageDialog(null, "This test this id exist","Please enter new test",JOptionPane.ERROR_MESSAGE);
                            }
                }
            
    }//GEN-LAST:event_InsertBActionPerformed

    private void UpdateBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBMouseClicked
     
    }//GEN-LAST:event_UpdateBMouseClicked

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
     
        DefaultTableModel model = (DefaultTableModel) jTableAddTest.getModel();
       
        int RowIndex = jTableAddTest.getSelectedRow();
       // model.removeRow(RowIndex);
      
        boolean enabled = false;
        if(jTextFieldID.getText().equals("")|| 
               jTextFieldDate.getText().equals("")|| 
               jTextFieldName.getText().equals("")||
               jTextAreaDesctiption.getText().equals("")||
               jTextFieldsIN.getText().equals("")){
           JOptionPane.showMessageDialog(null, "We did'nt add information","Fill out Information",JOptionPane.ERROR_MESSAGE);
       
         }else{
                enabled =true;
                //MessageFormat  header = new MessageFormat("\nLaboratory Test Report\n\n\n "+model.getDataVector().elementAt(jTableAddTest.getSelectedRow()).toString()+"\n");
               // MessageFormat  footer = new MessageFormat("\nDoctor Signature:______________  Date:___ /___ /_____ \\n\n"+"Page{0,number,integer}");
                MessageFormat  header = new MessageFormat("Laboratory Test Report\n\n\n");
                MessageFormat  footer = new MessageFormat("\nDoctor Signature:______________  Date:___ /___ /_____ ");
            try{

               jTableAddTest.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            }catch(java.awt.print.PrinterException e){
                System.err.format("Cannot print%s%n", e.getMessage());
            }
         }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void DeleteRowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowBActionPerformed
    
        DefaultTableModel model = (DefaultTableModel) jTableAddTest.getModel();
        int RowIndex = jTableAddTest.getSelectedRow();
       
      
          
         if(jTextFieldID.getText().equals("")|| 
               jTextFieldDate.getText().equals("")|| 
               jTextFieldName.getText().equals("")||
               jTextAreaDesctiption.getText().equals("")||
               jTextFieldsIN.getText().equals(""))
      
        {
           JOptionPane.showMessageDialog(null, "We did'nt select test","Select test",JOptionPane.ERROR_MESSAGE);
       
        }
        else
        {
           String query = "Delete from LabTest where TestID = " + jTextFieldID.getText();
               
           ConnectJavaOracle.rs = ConnectJavaOracle.processSearchQuery(query);
           JOptionPane.showMessageDialog(null, "We delete test successfully","Delete",JOptionPane.WARNING_MESSAGE);
           System.out.println(query);
           
            jTextFieldID.setText("");
            jTextFieldDate.setText("");
            jTextFieldName.setText("");
            jTextAreaDesctiption.setText("");
            jTextFieldsIN.setText("");
            model.removeRow(RowIndex);
           
            DeleteRowB.setEnabled(false);
            InsertB.setEnabled(false);
            UpdateB.setEnabled(false);
           
        }
    }//GEN-LAST:event_DeleteRowBActionPerformed

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
       String query = "UPDATE LabTest SET TestDate = to_DATE('"+jTextFieldDate.getText()+"','dd/mm/yyyy')" +
                 ",TestName = '"+ jTextFieldName.getText()+
                 "',TestDescription='" +jTextAreaDesctiption.getText()+
                  "',Insurance_Number='" +jTextFieldsIN.getText()+"' where TestID =" + jTextFieldID.getText() ;
         System.out.println(query);
         
        ConnectJavaOracle.rs = ConnectJavaOracle.processSearchQuery(query);
        JOptionPane.showMessageDialog(null, "Test update successfully","Update",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_UpdateBActionPerformed

    private void jTableAddTestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableAddTestFocusGained
       
    }//GEN-LAST:event_jTableAddTestFocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ConnectJavaOracle.openOracleConnection("scott", "tiger"); 
       
        if(LoginForm.role.equals("Patient"))
        {
            
            DeleteRowB.setEnabled(false);
            InsertB.setEnabled(false);
            UpdateB.setEnabled(false);
        }
        else
        {
            DeleteRowB.setEnabled(true);
            InsertB.setEnabled(true);
            UpdateB.setEnabled(true);
        
        }
        if(jTextFieldID.getText().equals("")|| 
               jTextFieldDate.getText().equals("")|| 
               jTextFieldName.getText().equals("")||
               jTextAreaDesctiption.getText().equals("")||
               jTextFieldsIN.getText().equals("")){
            
            DeleteRowB.setEnabled(false);
            InsertB.setEnabled(false);
            UpdateB.setEnabled(false);
       
        }
        else
        {
            DeleteRowB.setEnabled(true);
            InsertB.setEnabled(true);
            UpdateB.setEnabled(true);
          
        }
          
        if(LoginForm.role.equals("Patient")){
             PatientLastNameL.setText(LoginForm.db_patient_lname +" "+LoginForm.db_patient_fname );
             System.out.println(LoginForm.db_patient_lname);
        }
        else
        {
           DRL.setText(LoginForm.name);
            
        }
        
      
    }//GEN-LAST:event_formWindowActivated
int xx=0;
int yy=0;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {                                     
       xx=evt.getX();
       yy=evt.getY();  
    }                                    

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x=evt.getXOnScreen();
       int y=evt.getYOnScreen();
       this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL_B;
    private java.awt.Label DRL;
    private java.awt.Label DR_L;
    private java.awt.Label DR_L1;
    private java.awt.Label DR_L2;
    private javax.swing.JButton DeleteRowB;
    private javax.swing.JLabel Hide;
    private javax.swing.JTextField INSURANCE_NUMBER_TF;
    private javax.swing.JButton InsertB;
    private java.awt.Label InsuranceNumberL;
    private java.awt.Label InsuranceNumberL1;
    private java.awt.Label InsuranceNumberL2;
    private java.awt.Label InsuranceNumberL3;
    private java.awt.Label InsuranceNumberL4;
    private java.awt.Label InsuranceNumberL5;
    private java.awt.Label PatientLastNameL;
    private javax.swing.JButton SearchB;
    private javax.swing.JButton UpdateB;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAddTest;
    private javax.swing.JTextArea jTextAreaDesctiption;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldsIN;
    private javax.swing.JLabel xClose;
    // End of variables declaration//GEN-END:variables
}
